// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbyO7euJf9hCpwULdt1K7afeA2qCb0rWY',
    appId: '1:1085822556187:web:5537a0b532aa0cf1a540be',
    messagingSenderId: '1085822556187',
    projectId: 'cafe-fullstack',
    authDomain: 'cafe-fullstack.firebaseapp.com',
    storageBucket: 'cafe-fullstack.appspot.com',
    measurementId: 'G-P3QCV0LBRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDixe8i_qrUOFS3tJ5PYk48nBXAOcIMsBo',
    appId: '1:1085822556187:android:316e0f796e99e691a540be',
    messagingSenderId: '1085822556187',
    projectId: 'cafe-fullstack',
    storageBucket: 'cafe-fullstack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcFxoJD_IHDtGj-JPBTFLYu1LC65SpD4o',
    appId: '1:1085822556187:ios:61cd426534b50f0ba540be',
    messagingSenderId: '1085822556187',
    projectId: 'cafe-fullstack',
    storageBucket: 'cafe-fullstack.appspot.com',
    androidClientId: '1085822556187-7t08fvnc5v7ag6v6sh58s8f30usohplv.apps.googleusercontent.com',
    iosClientId: '1085822556187-heemu0dmrlrh2pa0b7n3khre0t7ketuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcFxoJD_IHDtGj-JPBTFLYu1LC65SpD4o',
    appId: '1:1085822556187:ios:61cd426534b50f0ba540be',
    messagingSenderId: '1085822556187',
    projectId: 'cafe-fullstack',
    storageBucket: 'cafe-fullstack.appspot.com',
    androidClientId: '1085822556187-7t08fvnc5v7ag6v6sh58s8f30usohplv.apps.googleusercontent.com',
    iosClientId: '1085822556187-heemu0dmrlrh2pa0b7n3khre0t7ketuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbyO7euJf9hCpwULdt1K7afeA2qCb0rWY',
    appId: '1:1085822556187:web:0d9b3641ab1091eca540be',
    messagingSenderId: '1085822556187',
    projectId: 'cafe-fullstack',
    authDomain: 'cafe-fullstack.firebaseapp.com',
    storageBucket: 'cafe-fullstack.appspot.com',
    measurementId: 'G-NZ1V9Q91NV',
  );

}